En Croissant: Always install newest rust
rust 1.87 is required
error: rustc 1.85.0 is not supported by the following packages:
  zbus@5.14.0 requires rustc 1.87
  zbus_macros@5.14.0 requires rustc 1.87
  zvariant@5.10.0 requires rustc 1.87
  zvariant@5.10.0 requires rustc 1.87
  zvariant_derive@5.10.0 requires rustc 1.87